#### Tech Challenge - Fase 1 - Data Analysis and Exploration

**Contexto**

Atuando como Expert em Data Analytics em uma empresa que exporta vinhos do Brasil para o mundo todo em uma área recém-criada dentro da empresa sendo responsável pelos relatórios iniciais a serem apresentados, explicando a quantidade de vinhos exportados e os fatores externos que podem vir a surgir e que interferem nas análises:

1. Dados climáticos
2. Dados demográficos
3. Dados econômicos
4. Dados de avaliações de vinhos

Sendo necessario a criação de uma tabela contendo as seguintes informações:

a. País de origem (Brasil)
b. País de destino
c. Quantidade em litros de vinho exportado (utilize: 1KG =1L)
d. Valor em US$

Com os dados fornecido de vinícola parceira e que podem ser encontrados aqui através do seguinte link:

 http://vitibrasil.cnpuv.embrapa.br/index.php?opcao=opt_01

#### Importação de pacotes, bibliotecas e criação de funções (DEF)

In [81]:
import pandas as pd

##### Tratar base de dados

In [82]:
# Caminho onde esta o arquivo
caminho_arquivo = r"C:\Users\ricar\OneDrive\Cursos\Pós Graduação\Data Analytics - FIAP\02 - Fase 1 - Data Analysis and Exploration\05 - Atividade a ser entregue até 03_06 - Em grupo\Base\ExpVinho.csv"

# Lista vazia para armazenar os dados
dados = []

with open(caminho_arquivo, encoding='utf-8') as f:
    linhas = f.readlines()

# Separar o cabeçalho original
cabecalho_raw = linhas[0].strip().split()

# Definir colunas iniciais fixas
colunas = ['Id', 'País']

# Selecionar os anos
anos = cabecalho_raw[2:]

# Agrupar pares de colunas por ano como 'Ano_Quantidade' e 'Ano_Valor'
for i in range(0, len(anos), 2):
    ano = anos[i]
    colunas.append(f"{ano}_quantidade_kg")
    colunas.append(f"{ano}_valor_usd")

# Lê os dados
for linha in linhas[1:]:
    partes = linha.strip().split()
    id = partes[0]

    # Juntar os campos do país até encontrar o início dos valores (número)
    i = 1
    while not partes[i].isdigit():
        i += 1
    pais = ' '.join(partes[1:i])
    valores = partes[i:]
    dados.append([id, pais] + valores)

# Criar o DataFrame e ajustar o nome
df_vinhos = pd.DataFrame(dados, columns=colunas)
df_vinhos = df_vinhos.rename(columns={'País': 'pais','Id':'id'})
df_vinhos.head()

,id,pais,1970_quantidade_kg,1970_valor_usd,1971_quantidade_kg,1971_valor_usd,1972_quantidade_kg,1972_valor_usd,1973_quantidade_kg,1973_valor_usd,...,2020_quantidade_kg,2020_valor_usd,2021_quantidade_kg,2021_valor_usd,2022_quantidade_kg,2022_valor_usd,2023_quantidade_kg,2023_valor_usd,2024_quantidade_kg,2024_valor_usd
0,1,Afeganistão,0,0,0,0,0,0,0,0,...,0,0,11,46,0,0,0,0,0,0
1,2,África do Sul,0,0,0,0,0,0,0,0,...,4,21,0,0,0,0,117,698,103,1783
2,3,"Alemanha, República Democrática",0,0,0,0,4168,2630,12000,8250,...,6261,32605,2698,6741,7630,45367,4806,31853,6666,48095
3,4,Angola,0,0,0,0,0,0,0,0,...,0,0,0,0,4068,4761,0,0,0,0
4,5,Anguilla,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [83]:
# Selecionar o nome das colunas
anos = df_vinhos.columns[2:]
anos

# Fazer um copia do data frame
df_vinhos_tratado = df_vinhos.copy()

# Despivotar o data frame
df_vinhos_tratado = df_vinhos.melt(id_vars=['id','pais'],value_vars=anos, var_name='ano_tipo', value_name='valor') 

# Criar duas novas coluna com o ano e o tipo
df_vinhos_tratado['tipo'] = df_vinhos_tratado['ano_tipo'].str.split('_', n=1).str[1]
df_vinhos_tratado['ano'] = df_vinhos_tratado['ano_tipo'].str.split('_', n=1).str[0]

# Remover coluna não necessaria
df_vinhos_tratado = df_vinhos_tratado.drop(columns=['ano_tipo'])

# Pivotar a coluna tipo com o valor 
df_vinhos_tratado = df_vinhos_tratado.pivot(index=['id', 'pais', 'ano'],columns='tipo',values='valor')
df_vinhos_tratado = df_vinhos_tratado.reset_index()

df_vinhos_tratado.query('pais == "África do Sul"').tail()

tipo id           pais   ano quantidade_kg valor_usd
2965  2  África do Sul  2020             4        21
2966  2  África do Sul  2021             0         0
2967  2  África do Sul  2022             0         0
2968  2  África do Sul  2023           117       698
2969  2  África do Sul  2024           103      1783