#### Tech Challenge - Fase 1 - Data Analysis and Exploration

**Contexto**

Atuando como Expert em Data Analytics em uma empresa que exporta vinhos do Brasil para o mundo todo em uma área recém-criada dentro da empresa sendo responsável pelos relatórios iniciais a serem apresentados, explicando a quantidade de vinhos exportados e os fatores externos que podem vir a surgir e que interferem nas análises:

1. Dados climáticos
2. Dados demográficos
3. Dados econômicos
4. Dados de avaliações de vinhos

Sendo necessario a criação de uma tabela contendo as seguintes informações:

a. País de origem (Brasil)
b. País de destino
c. Quantidade em litros de vinho exportado (utilize: 1KG =1L)
d. Valor em US$

Com os dados fornecido de vinícola parceira e que podem ser encontrados aqui através do seguinte link:

 http://vitibrasil.cnpuv.embrapa.br/index.php?opcao=opt_01

##### Importação de pacotes, bibliotecas e criação de funções (DEF)

In [124]:
# Importar biblioteca completa
import pandas as pd

# Importar função especifica de um módulo
from datetime import datetime

##### Tratar base de dados

In [125]:
# Caminho onde esta o arquivo
caminho_arquivo = r"C:\Users\ricar\OneDrive\Cursos\Pós Graduação\Data Analytics - FIAP\02 - Fase 1 - Data Analysis and Exploration\05 - Atividade a ser entregue até 03_06 - Em grupo\Base\ExpVinho.csv"

# Lista vazia para armazenar os dados
dados = []

with open(caminho_arquivo, encoding='utf-8') as f:
    linhas = f.readlines()

# Separar o cabeçalho original
cabecalho_raw = linhas[0].strip().split()

# Definir colunas iniciais fixas
colunas = ['Id', 'País']

# Selecionar os anos
anos = cabecalho_raw[2:]

# Agrupar pares de colunas por ano como 'Ano_Quantidade' e 'Ano_Valor'
for i in range(0, len(anos), 2):
    ano = anos[i]
    colunas.append(f"{ano}_quantidade_kg")
    colunas.append(f"{ano}_valor_usd")

# Lê os dados
for linha in linhas[1:]:
    partes = linha.strip().split()
    id = partes[0]

    # Juntar os campos do país até encontrar o início dos valores (número)
    i = 1
    while not partes[i].isdigit():
        i += 1
    pais = ' '.join(partes[1:i])
    valores = partes[i:]
    dados.append([id, pais] + valores)

# Criar o DataFrame e ajustar o nome
df_vinhos = pd.DataFrame(dados, columns=colunas)
df_vinhos = df_vinhos.rename(columns={'País': 'pais','Id':'id'})
df_vinhos.head()

,id,pais,1970_quantidade_kg,1970_valor_usd,1971_quantidade_kg,1971_valor_usd,1972_quantidade_kg,1972_valor_usd,1973_quantidade_kg,1973_valor_usd,...,2020_quantidade_kg,2020_valor_usd,2021_quantidade_kg,2021_valor_usd,2022_quantidade_kg,2022_valor_usd,2023_quantidade_kg,2023_valor_usd,2024_quantidade_kg,2024_valor_usd
0,1,Afeganistão,0,0,0,0,0,0,0,0,...,0,0,11,46,0,0,0,0,0,0
1,2,África do Sul,0,0,0,0,0,0,0,0,...,4,21,0,0,0,0,117,698,103,1783
2,3,"Alemanha, República Democrática",0,0,0,0,4168,2630,12000,8250,...,6261,32605,2698,6741,7630,45367,4806,31853,6666,48095
3,4,Angola,0,0,0,0,0,0,0,0,...,0,0,0,0,4068,4761,0,0,0,0
4,5,Anguilla,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [126]:
# Selecionar o nome das colunas
anos = df_vinhos.columns[2:]
anos

# Fazer um copia do data frame
df_vinhos_tratado = df_vinhos.copy()

# Despivotar o data frame
df_vinhos_tratado = df_vinhos.melt(id_vars=['id','pais'],value_vars=anos, var_name='ano_tipo', value_name='valor') 

# Criar duas novas coluna com o ano e o tipo
df_vinhos_tratado['tipo'] = df_vinhos_tratado['ano_tipo'].str.split('_', n=1).str[1]
df_vinhos_tratado['ano'] = df_vinhos_tratado['ano_tipo'].str.split('_', n=1).str[0]

# Remover coluna não necessaria
df_vinhos_tratado = df_vinhos_tratado.drop(columns=['ano_tipo'])

# Pivotar a coluna tipo com o valor 
df_vinhos_tratado = df_vinhos_tratado.pivot(index=['id', 'pais', 'ano'],columns='tipo',values='valor')
df_vinhos_tratado = df_vinhos_tratado.reset_index()

# Converter colunas para o formato númerico
colunas_altercao = ['quantidade_kg','valor_usd']
df_vinhos_tratado[colunas_altercao] = df_vinhos_tratado[colunas_altercao].apply(pd.to_numeric, errors='coerce')

# Filtrar ultimos dados
df_vinhos_tratado.query('pais == "África do Sul"').tail()

tipo id           pais   ano  quantidade_kg  valor_usd
2965  2  África do Sul  2020              4         21
2966  2  África do Sul  2021              0          0
2967  2  África do Sul  2022              0          0
2968  2  África do Sul  2023            117        698
2969  2  África do Sul  2024            103       1783

##### Analise do preço médio

Pergunta = Qual a elasticidade do preço por kg com relação à quantidade exportada?

In [127]:
# Limitar os ultimos anos
delta_anos = 15
ano_atual = datetime.now().year
limite = str(ano_atual-delta_anos)

df_vinhos_ultimo = df_vinhos_tratado.copy()
df_vinhos_ultimo = df_vinhos_ultimo[df_vinhos_ultimo['ano'] >=  limite].sort_values(by='ano')
df_vinhos_ultimo

tipo   id                      pais   ano  quantidade_kg  valor_usd
40      1               Afeganistão  2010              0          0
2515   14                   Bahamas  2010           3175      12759
3395   27                  Camarões  2010              0          0
4440   44                      Cuba  2010              0          0
1250  119  São Vicente e Granadinas  2010              0          0
...   ...                       ...   ...            ...        ...
4399   43                   Croácia  2024             23         44
2474  139                   Vanuatu  2024              0          0
1264  119  São Vicente e Granadinas  2024              0          0
7259   90                     Malta  2024           6302      16586
7754   99                   Nigéria  2024            808       2052

[2115 rows x 5 columns]

In [128]:
# Agrupar os dados
df_vinhos_ultimo_rank = df_vinhos_ultimo.copy()
df_vinhos_ultimo_rank = df_vinhos_ultimo_rank.groupby('pais')[['quantidade_kg','valor_usd']].sum().reset_index()

# Fazer o ranking
rank = 5
df_vinhos_ultimo_rank['ranking'] = df_vinhos_ultimo_rank['quantidade_kg'].rank(ascending=False, method='max')
df_vinhos_ultimo_rank = df_vinhos_ultimo_rank.query('ranking <= @rank').sort_values(by='ranking')
df_vinhos_ultimo_rank

tipo            pais  quantidade_kg  valor_usd  ranking
102         Paraguai       34021588   47591976      1.0
112           Rússia       10909283   17419774      2.0
50    Estados Unidos        3287390    9297709      3.0
65             Haiti        2797418    3906144      4.0
49           Espanha        1988248    3803901      5.0

In [ ]:
# Calcular o preço médio

df_vinhos_pm =  df_vinhos_ultimo.query('quantidade_kg > 0').copy()

# Fazer o filtro 
df_vinhos_pm = df_vinhos_pm[df_vinhos_pm['pais'].isin(df_vinhos_ultimo_rank['pais'])]

# Calcular o preço médio 
df_vinhos_pm['pm'] = (df_vinhos_pm['valor_usd'] / df_vinhos_pm['quantidade_kg']).fillna(0)

# Ordernar os dados
df_vinhos_pm = df_vinhos_pm.sort_values(by=['pais','ano'])

# Calcular a elasticidade-preço da oferta (EPO)
df_vinhos_pm['var_pct_qtd'] = df_vinhos_pm.groupby('pais')['quantidade_kg'].pct_change()
df_vinhos_pm['var_pct_pm'] = df_vinhos_pm.groupby('pais')['pm'].pct_change()

df_vinhos_pm["elasticidade"] = (df_vinhos_pm["var_pct_pm"] / df_vinhos_pm["var_pct_qtd"])

df_vinhos_pm

tipo,id,pais,ano,quantidade_kg,valor_usd,pm,var_pct_qtd,var_pct_pm,elasticidade
4936,52,Espanha,2011,5206,24618,4.728774,NaN,NaN,NaN
4938,52,Espanha,2013,1972980,3748940,1.900141,377.981944,-0.598175,-0.001583
4943,52,Espanha,2018,6123,22631,3.696064,-0.996897,0.945153,-0.948095
4944,52,Espanha,2019,3540,1353,0.382203,-0.421852,-0.896592,2.125370
4945,52,Espanha,2020,28,126,4.500000,-0.992090,10.773836,-10.859732
4948,52,Espanha,2023,180,4171,23.172222,5.428571,4.149383,0.764360
4949,52,Espanha,2024,191,2062,10.795812,0.061111,-0.534105,-8.739908
4990,53,Estados Unidos,2010,228968,478630,2.090379,NaN,NaN,NaN
4991,53,Estados Unidos,2011,306787,1030254,3.358206,0.339868,0.606506,1.784530
4992,53,Estados Unidos,2012,146585,303986,2.073787,-0.522193,-0.382472,0.732434
4993,53,Estados Unidos,2013,245368,786556,3.205618,0.673896,0.545780,0.809888
4994,53,Estados Unidos,2014,222267,494216,2.223524,-0.094148,-0.306366,3.254081
4995,53,Estados Unidos,2015,195896,524109,2.675445,-0.118646,0.203245,-1.713047
4996,53,Estados Unidos,2016,258072,687411,2.663640,0.317393,-0.004412,-0.013902
4997,53,Estados Unidos,2017,132688,1523699,11.483322,-0.485849,3.311138,-6.815160
4998,53,Estados Unidos,2018,169109,512519,3.030702,0.274486,-0.736078,-2.681659
4999,53,Estados Unidos,2019,209765,616274,2.937926,0.240413,-0.030612,-0.127332
5000,53,Estados Unidos,2020,300178,610793,2.034769,0.431020,-0.307413,-0.713221
5001,53,Estados Unidos,2021,111085,203554,1.832417,-0.629936,-0.099448,0.157869
5002,53,Estados Unidos,2022,220373,447893,2.032431,0.983823,0.109154,0.110948
5003,53,Estados Unidos,2023,229839,429091,1.866920,0.042954,-0.081435,-1.895851
5004,53,Estados Unidos,2024,310410,648724,2.089894,0.350554,0.119434,0.340701
5870,68,Haiti,2010,2700,3750,1.388889,NaN,NaN,NaN
5878,68,Haiti,2018,79500,144425,1.816667,28.444444,0.308000,0.010828
5879,68,Haiti,2019,81873,129803,1.585419,0.029849,-0.127292,-4.264535
5880,68,Haiti,2020,399128,471152,1.180453,3.874965,-0.255431,-0.065918
5881,68,Haiti,2021,670379,831181,1.239867,0.679609,0.050331,0.074059
5882,68,Haiti,2022,553503,741014,1.338771,-0.174343,0.079770,-0.457545
5883,68,Haiti,2023,559645,871661,1.557525,0.011097,0.163399,14.725112
5884,68,Haiti,2024,450690,713158,1.582369,-0.194686,0.015951,-0.081933
535,107,Paraguai,2010,510989,449197,0.879074,NaN,NaN,NaN
536,107,Paraguai,2011,240168,276281,1.150366,-0.529994,0.308611,-0.582292
537,107,Paraguai,2012,354824,428279,1.207018,0.477399,0.049247,0.103158
538,107,Paraguai,2013,481564,680828,1.413785,0.357191,0.171304,0.479586
539,107,Paraguai,2014,521847,908028,1.740027,0.083650,0.230758,2.758601
540,107,Paraguai,2015,495428,741370,1.496423,-0.050626,-0.140000,2.765382
541,107,Paraguai,2016,985739,1655417,1.679366,0.989672,0.122254,0.123529
542,107,Paraguai,2017,2393468,4274650,1.785965,1.428095,0.063475,0.044448
543,107,Paraguai,2018,3234168,5494321,1.698836,0.351248,-0.048785,-0.138892
544,107,Paraguai,2019,2419537,3826587,1.581537,-0.251883,-0.069047,0.274123
545,107,Paraguai,2020,3299013,3869243,1.172849,0.363489,-0.258412,-0.710921
546,107,Paraguai,2021,6522527,7192362,1.102696,0.977115,-0.059814,-0.061215
547,107,Paraguai,2022,5076670,7156293,1.409643,-0.221671,0.278361,-1.255738
548,107,Paraguai,2023,3780378,5517263,1.459447,-0.255343,0.035331,-0.138367
549,107,Paraguai,2024,3705268,5121857,1.382318,-0.019868,-0.052849,2.659939
1087,116,Rússia,2012,4528176,2103968,0.464639,NaN,NaN,NaN
1088,116,Rússia,2013,5893291,14795694,2.510600,0.301471,4.403332,14.606140
1089,116,Rússia,2014,190656,61440,0.322256,-0.967649,-0.871642,0.900783
1090,116,Rússia,2015,47664,18240,0.382679,-0.750000,0.187500,-0.250000
1095,116,Rússia,2020,1463,8550,5.844156,-0.969306,14.271702,-14.723629
1096,116,Rússia,2021,181931,312926,1.720026,123.354751,-0.705684,-0.005721
1097,116,Rússia,2022,66046,118618,1.795991,-0.636972,0.044165,-0.069336
1099,116,Rússia,2024,56,338,6.035714,-0.999152,2.360660,-2.362663